#!/bin/bash

while read -r line 
do 
  echo $line
  if [[ ${line:0:9} == "#LAUNCHER" ]]
  then 
    cmd=$(echo $line | cut -d" " -f2-)
    eval $cmd
  elif [[ -z "${MEM_PER_TASK}" ]]
  then
    if [[ -z "${LAUNCHER_CORES_PER_TASK}" ]]; then export LAUNCHER_CORES_PER_TASK=1; fi
    echo "srun -n 1 -c $LAUNCHER_CORES_PER_TASK $line"
    srun -N 1 -n 1 -c $LAUNCHER_CORES_PER_TASK $line &
    echo "task launched!"
  else
    echo "srun -n 1 -c $LAUNCHER_CORES_PER_TASK --mem=$MEM_PER_TASK $line"
    srun -n 1 -c $LAUNCHER_CORES_PER_TASK --mem=$MEM_PER_TASK $line &
    echo "task launched!"
  fi
  # sleep 1 # be nice to slurm
done < $1
